---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(viridis)
library(ggtern)
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
data <- read_csv("data/MDH_Beast_AllChem_Apr22.csv") %>%
  filter(!Site %in% c("MSL", "MSTR1", "MSU", "RT0"))

elements <- read_csv("data/Periodic Table of Elements.csv") %>% select(Symbol, AtomicMass)
```


```{r}
```

```{r}
data_long <- data %>% select(Date,Site, Reach, Dist, Na_ppb, Mg_ppb, 
                             Al_ppb, Si_ppb, K_ppb, Ca_ppb, Fe_ppb,
                             S_ppm_as_SO4) %>%
  pivot_longer(Na_ppb:S_ppm_as_SO4) %>%
  mutate(Element = substr(name, 1, nchar(name) - 4)) %>%
  left_join(elements, by = c("Element" = "Symbol")) %>%
  mutate(mol_L = (value / 1000000) / AtomicMass)

data_wide_molL <- data_long %>% select(Site, Date, Reach, Dist, Element, mol_L) %>%
  pivot_wider(values_from = mol_L, names_from = Element)

data_long %>% 
  ggplot(aes(x = Reach, y = value, fill = Date))+
  geom_boxplot()+
  facet_wrap(vars(name), scale = "free")+
  theme_classic()
```
```{r}
data_long %>% filter(name %in% c("Ca_ppb","K_ppb","Mg_ppb","Si_ppb","Na_ppb" ))%>%
  ggplot(aes(x = Dist, y = value, color = Reach, pch = Date))+
  geom_point()+
  geom_line()+
  facet_wrap(vars(name), scale = "free")+
  scale_colour_manual(values = cbPalette, name = "Streams")+
  theme_classic()
```
```{r}
lowbf <- data_long %>% filter(Date == "9/10/21")
highbf <- data_long %>% filter(Date == "3/8/22")

flows_as_cols <- left_join(highbf, lowbf, by = c("Reach","Dist", "name"), suffix = c("high", "low"))

flows_as_cols %>% 
  ggplot(aes(x = Dist, y = valuehigh - valuelow, color = Reach))+
  geom_point()+
  geom_line()+
  facet_wrap(vars(name), scale = "free")+
  theme_classic()

```

```{r}
data %>%
  ggplot(aes(x = Ca_ppb, y = Si_ppb, color = Reach))+#, size = Dist, pch = Date))+
  geom_point()+
  theme_classic()
```

```{r}
data %>% ggtern(aes(x = Ca_ppb, y = Mg_ppb, z = Na_ppb + K_ppb, 
                    color = Reach))+
  geom_point()+
  theme_minimal()
```

```{r}
data_wide_molL %>%
  ggplot(aes(x = Dist, y = Na + Mg + Ca + Si , color = Reach))+
  geom_point()+
  theme_classic()
```
```{r}


data_long %>% filter(name == "Ca_ppb") %>%
  ggplot(aes(x = Dist, y = Reach, fill = value))+
    geom_line(color = "grey")+
  geom_point(size = 6, pch = 21)+
  theme_classic()+
  #scale_fill_continuous(na.value = "transparent")+
  scale_fill_viridis(na.value = "transparent")+
  ggtitle(" Ca (ppb)")
```
```{r, fig.height=3, fig.width=6}
data_long %>% filter(name == "Si_ppb" ) %>%
  ggplot(aes(x = Dist, y = value/1000, color = Reach, pch = Date))+
  geom_point()+
  geom_line()+
  ylab("Si (mg/L)")+
  xlab("Distance upstream (m)")+
  scale_color_discrete(name = "Stream", labels = c("North side", "South side"))+
  theme_classic()
```

```{r}


# Create a data frame defining the three regions
regions <- data.frame(
  region = c("Evaporites", "Silicates", "Carbonates"),
  xmin = c(0.12, 0.22, 20),
  xmax = c(.28,   0.65,   80),
  ymin = c(0.015, 0.18, 6),
  ymax = c(0.05,  0.65,   12)
)

data_wide_molL |>
  ggplot(aes(x = Ca / Na, y = Mg / Na, color = Reach))+
  geom_point()+
  theme_classic()+
   # Draw rectangular regions
  geom_rect(data = regions,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax,
                fill = region),
            alpha = 0.2,
            color = "black",
            inherit.aes = FALSE) +
  # Add labels centered in each region
  geom_text(data = regions,
            aes(x = sqrt(xmin * xmax),
                y = sqrt(ymin * ymax),
                label = region),
            size = 5,
            inherit.aes = FALSE) +
  # Log scales
  scale_x_log10(name = "Ca/Na",
                limits = c(0.1, 100)) +
  scale_y_log10(name = "Mg/Na",
                limits = c(0.01, 10)) 
  


ggplot() +
  
  # Draw rectangular regions
  geom_rect(data = regions,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax,
                fill = region),
            alpha = 0.2,
            color = "black") +
  
  # Add labels centered in each region
  geom_text(data = regions,
            aes(x = sqrt(xmin * xmax),
                y = sqrt(ymin * ymax),
                label = region),
            size = 5) +
  
  # Log scales
  scale_x_log10(name = "Ca/Na",
                limits = c(0.1, 100)) +
  scale_y_log10(name = "Mg/Na",
                limits = c(0.01, 10)) +
  
  # Clean theme
  theme_classic() +
  theme(legend.position = "none")
```

